// All roles and statuses live here so models, services, validation
// and tests use exactly the same values.

const ROLES = {
    ADMIN: "ADMIN",
    INVENTORY_MANAGER: "INVENTORY_MANAGER",
    STAFF: "STAFF",
    SUPPLIER: "SUPPLIER"
};

// Used by users, products, categories, warehouses and suppliers
const RECORD_STATUS = {
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE"
};

const TRANSFER_STATUS = {
    REQUESTED: "REQUESTED",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    DISPATCHED: "DISPATCHED",
    RECEIVED: "RECEIVED",
    CANCELLED: "CANCELLED"
};

const ORDER_STATUS = {
    PENDING: "PENDING",
    CONFIRMED: "CONFIRMED",
    PROCESSING: "PROCESSING",
    PACKED: "PACKED",
    SHIPPED: "SHIPPED",
    DELIVERED: "DELIVERED",
    CANCELLED: "CANCELLED"
};

const PURCHASE_STATUS = {
    DRAFT: "DRAFT",
    PENDING: "PENDING",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    ORDERED: "ORDERED",
    PARTIALLY_RECEIVED: "PARTIALLY_RECEIVED",
    RECEIVED: "RECEIVED",
    CANCELLED: "CANCELLED"
};

const STOCK_TRANSACTION_TYPE = {
    STOCK_IN: "STOCK_IN",
    STOCK_OUT: "STOCK_OUT",
    TRANSFER_IN: "TRANSFER_IN",
    TRANSFER_OUT: "TRANSFER_OUT",
    ADJUSTMENT: "ADJUSTMENT"
};

// What caused a stock transaction
const STOCK_REFERENCE_TYPE = {
    MANUAL: "MANUAL",
    ORDER: "ORDER",
    PURCHASE_ORDER: "PURCHASE_ORDER",
    TRANSFER: "TRANSFER"
};

const NOTIFICATION_TYPE = {
    LOW_STOCK: "LOW_STOCK",
    NEW_ORDER: "NEW_ORDER",
    ORDER_STATUS_CHANGED: "ORDER_STATUS_CHANGED",
    PURCHASE_APPROVED: "PURCHASE_APPROVED",
    PURCHASE_RECEIVED: "PURCHASE_RECEIVED",
    STOCK_TRANSFER: "STOCK_TRANSFER",
    SYSTEM_ALERT: "SYSTEM_ALERT"
};

module.exports = {
    ROLES,
    RECORD_STATUS,
    TRANSFER_STATUS,
    ORDER_STATUS,
    PURCHASE_STATUS,
    STOCK_TRANSACTION_TYPE,
    STOCK_REFERENCE_TYPE,
    NOTIFICATION_TYPE
};
